# Generated by Django 3.2.6 on 2024-02-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='applicant_name',
            new_name='name',
        ),
    ]
